services:
    Flowd\Phirewall\Middleware:
        autowire: true
        public: true
        arguments:
            $config: '@Flowd\Phirewall\Config'

    Flowd\Typo3Firewall\ConfigFactory:
        autowire: true

    Flowd\Phirewall\Config:
        factory: ['@Flowd\Typo3Firewall\ConfigFactory', 'fromConfigurationFile']
