services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Flowd\Typo3Firewall\:
        resource: '../Classes/*'

    Flowd\Phirewall\Middleware:
        autowire: true
        public: true
        arguments:
            $config: '@Flowd\Phirewall\Config'

    Flowd\Phirewall\Config:
        factory: ['@Flowd\Typo3Firewall\ConfigFactory', 'fromConfigurationFile']
